### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by winstonrc** [kevle1/paris-2024-olympic-api#1]
I am getting the following error when trying to access the api:
`CORS error: No 'Access-Control-Allow-Origin' header is present on the requested resource`

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

**Comment by kevle1** [comment]
Added `Access-Control-Allow-Origin` header on response and support for the OPTIONS method :) 

```
curl -i https://api.olympics.kevle.xyz/medals
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
...
```
