### ISSUE TITLE
Kosovo Country Code Incorrect

### ISSUE THREAD

**Issue by vinaykapadia** [kevle1/paris-2024-olympic-api#11]
Kosovo is returning country code of KR which is Korea. Kosovo should be returning XK. Thanks!

**Comment by kevle1** [comment]
Thanks for raising, there was an error in the mapping file. Should be updated now. 

https://api.olympics.kevle.xyz/medals?country=kos

**Comment by vinaykapadia** [comment]
Awesome, thanks!
