### ISSUE TITLE
Paralympics support

### ISSUE THREAD

**Issue by michaeldaltonau** [kevle1/paris-2024-olympic-api#17]
It would be nice if this project also supported the 2024 Paralympics. The API isn't returning data yet as the first medal event isn't for a few more hours, but the endpoint _should_ be:

https://olympics.com/PG2024/data/CIS_MedalNOCs~lang=ENG~comp=PG2024.json

**Comment by kevle1** [comment]
Good call! Added https://api.olympics.kevle.xyz/paralympics/medals :)
