### ISSUE TITLE
Limited data 

### ISSUE THREAD

**Issue by EswaramoorthyKarthikeyan** [kevle1/paris-2024-olympic-api#2]
Its only showing limited data only

**Comment by kevle1** [comment]
Unfortunately it seems like the Olympics medal site loads some data dynamically meaning the results get cut off at ~19 countries when parsing the source. I'll have to figure out a workaround that keeps it performant (Selenium is pretty slow!). They didn't make this easy 😅

**Comment by EswaramoorthyKarthikeyan** [comment]
Thank you 👍🏻

**Comment by kevle1** [comment]
Added Wikipedia as a source for fetching all medals! Let me know how you go :) 

https://api.olympics.kevle.xyz/medals/all

**Comment by EswaramoorthyKarthikeyan** [comment]
It is showing incorrect data when performing a country-wise search

https://api.olympics.kevle.xyz/medals/all for all

https://api.olympics.kevle.xyz/medals?country=uzb


<img width="433" alt="Screenshot 2024-07-29 at 21 51 49" src="https://github.com/user-attachments/assets/98f5b812-f877-49c8-b46e-c08876021eaa">
<img width="348" alt="Screenshot 2024-07-29 at 21 52 07" src="https://github.com/user-attachments/assets/808fd16f-c5e0-4904-80c7-6be56e45e0dd">


please compare the result

**Comment by kevle1** [comment]
@EswaramoorthyKarthikeyan Should be fixed now! Let me know how you go

**Comment by EswaramoorthyKarthikeyan** [comment]
Working fine, thank you so much @kevle1

**Comment by michaeldaltonau** [comment]
@kevle1 you might find this endpoint useful:
https://olympics.com/OG2024/data/CIS_MedalNOCs~lang=ENG~comp=OG2024.json

**Comment by kevle1** [comment]
@llui85 Woah that's awesome. Much better than web scraping, will have a look at parsing that, cheers!

**Comment by michaeldaltonau** [comment]
The NOCs can also be listed with:
https://olympics.com/OG2024/data/MIS_NOCS~lang=ENG~comp=OG2024.json

although I don't know if that helps you much with the ISO mapping.

**Comment by michaeldaltonau** [comment]
> @llui85 Woah that's awesome. Much better than web scraping, will have a look at parsing that, cheers!

You're welcome! From what I can tell, you need to filter for records where `gender` = `TOT` and `sport` = `GLO` (I assume that's for global), and then what's left is the actual medal tallies.

**Comment by Danny-Engelman** [comment]
All ISO and IOC codes can be retrieved from the https://restcountries.com/ API

Example ioc:NED (Netherlands): https://restcountries.com/v3.1/alpha/NED

![](https://i.imgur.com/XNeXI67.png)
