### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by danielsitnik** [kevle1/paris-2024-olympic-api#3]
Not really an issue, I just wanted to thank you for providing this simple and straightforward API.

I made an app for the [Tidbyt](https://tidbyt.com) with it!
It is a retro-style display that sits on your desk and shows you relevant information.

This is how it looks running on the device:
![image](https://github.com/user-attachments/assets/0d394720-83e4-45bc-9f24-9b3634728180)

Ohh and don't worry, we cache the API result for 1 hour 😉

**Comment by kevle1** [comment]
That's awesome!
