### ISSUE TITLE
Inaccurate Data Parsing

### ISSUE THREAD

**Issue by sstar0016** [kevle1/paris-2024-olympic-api#6]
Really handy resource thank you!

Minor issue where the wikipedia data is sometimes parsed incorrectly
![image](https://github.com/user-attachments/assets/008fcbe8-6152-49fb-8285-349dd7ad64ff)
![image](https://github.com/user-attachments/assets/2a41fab2-1bd4-40c7-aa54-84c56df56027)

I think it stems from here
![image](https://github.com/user-attachments/assets/6259c557-4102-4736-8763-17f85d67e21d)

**Comment by kevle1** [comment]
Should be fixed now!
