### ISSUE TITLE
possible to add ISO 3166 Alpha - 2 (2 letter) code?

### ISSUE THREAD

**Issue by Danny-Engelman** [kevle1/paris-2024-olympic-api#8]
https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

Has 3 letter (you now add) and 2 letter codes for countries (alpha-3 and alpha-2)

Flags typically use 2 letter codes, would it be possible to add those?

Then adding flags is a breeze with the https://flagmeister.github.io Web Component

All required HTML then is ``<flag-jp></flag-jp>`` for Japan

https://jsfiddle.net/WebComponents/zxpev6d8/ creates a ``<olympic-medal-ranking>`` Web Component processing your API

Now displays incorrect flags because alpha-2 is not always the first 2 letters of alpha-3

![](https://i.imgur.com/PvaLZqE.png)

There is no ``<flag-ko>`` should be ``<flag-kr>``

Need be I will add a translation table

tnx!

**Comment by Danny-Engelman** [comment]
Hmm.. looks like one more issue, the page you scrape doesn't contain ISO 3166 codes but IOC country codes.

Germany is GER, but for ISO 3166 that should be DEU (and DE)

Nothing you can do about that (since you scrape a page), I have to add a translation table for flags (and have ChatGPT create that)

**Comment by kevle1** [comment]
Yep, unfortunately IOC uses their own codes. I made a quick mapping of [this Wikipedia page](https://en.wikipedia.org/wiki/Comparison_of_alphabetic_country_codes) Pycountry and this [NOC data source](https://olympics.com/OG2024/data/MIS_NOCS~lang=ENG~comp=OG2024.json). Should now return ISO codes

**Comment by Danny-Engelman** [comment]
Are you okay with me blogging about your API?

Draft: https://dev.to/dannyengelman/olympic-medal-ranking-web-component-2c1j-temp-slug-4981295?preview=dcccd605815c84f30f87b3e320527c9d6d3f1e43ddb03ba87d8cc8cb0cd5260c123b93e25d31e770397791018157f5cd64d827651246a06e00af4c27

I think I am about the only one who cares about ISO codes and flags.

You could clean up your JSON by removing the iso names:

instead of:

```
  "country": {
        "code": "GER",
        "iso_alpha_2": "DE",
        "iso_alpha_3": "DEU",
        "name": "Germany"
      },
```

do

```
  "country": {
        "code": "GER",
        "flag": "DE",
        "name": "Germany"
      },
```

**Comment by Danny-Engelman** [comment]
![](https://i.imgur.com/PTqrTzD.png)

Did you allow ``localhost`` / ``127.0.0.1`` today?

Do you want your API to be open for everyone? Or limit by URI?

If URI, my Github WebPages domain is: **https://olympic-medal-ranking.github.io**
